#!/bin/sh
#
# Will be named:
# /usr/share/initramfs-tools/hooks/ykfde
#

set -e

# set the defaults
CHALLENGE_FILE="/boot/yubikey-challenge"

# read defaults..
if [ -e /etc/default/ykfde ]; then
    . /etc/default/ykfde
fi

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules hid_generic usbhid usbcore ehci_hcd ehci_pci
copy_exec /usr/bin/ykchalresp

cp /${CHALLENGE_FILE} "${DESTDIR}/etc/yubikey-challenge"
cp /usr/share/ykfde/ykfde-keyscript "${DESTDIR}/sbin/ykfde-keyscript"
exit 0
