#!/bin/sh
#
# Will be named:
# /usr/share/initramfs-tools/hooks/ykfde
#

set -e

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules hid_generic usbhid usbcore ehci_hcd ehci_pci
copy_exec /usr/bin/ykchalresp

cp /boot/yubikey-challenge "${DESTDIR}/etc/yubikey-challenge"
cp /usr/share/ykfde/ykfde-keyscript "${DESTDIR}/sbin/ykfde-keyscript"
exit 0
