#! /bin/sh

### BEGIN INIT INFO
# Provides:          ykfde
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: update yubikey-challenge
# Description: update yubikey-challenge for LUKS
### END INIT INFO

N=/etc/init.d/ykfde

set -e

case "$1" in
    start|restart)
        /usr/sbin/ykfdectl update 
    ;;
    stop|reload|force-reload|status)
	;;
    *)
	    echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	    exit 1
	;;
esac

exit 0
